// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzWvUooJQwR4Sml9m1n5F-hFs6I-kx44Y',
    appId: '1:629286348967:android:e66cea9689dff3d82f1382',
    messagingSenderId: '629286348967',
    projectId: 'smarttrainer-b8a31',
    databaseURL: 'https://smarttrainer-b8a31-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarttrainer-b8a31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj9WkxZ1_1nxRvzsDEt-8nFTP7kcHVkn4',
    appId: '1:629286348967:ios:53da30bd936b6fe12f1382',
    messagingSenderId: '629286348967',
    projectId: 'smarttrainer-b8a31',
    databaseURL: 'https://smarttrainer-b8a31-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarttrainer-b8a31.appspot.com',
    iosClientId: '629286348967-u3h733fl0kkluk7n83bbfet4a8vtr0ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTrainer',
  );
}
